<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '',
    'Class ID' => '',
    'Content' => '',
    'Create Info' => '',
    'Delete' => '',
    'ID' => '',
    'Info Classes' => '',
    'Infos' => '',
    'Name' => '',
    'Open' => '',
    'Parent ID' => '',
    'Save' => '',
    'Sort' => '',
    'The requested page does not exist.' => '',
    'Update' => '',
    'Update Info Class: {name}' => '',
    'Update Info: {name}' => '',
    'Виджеты' => '',
    'Добавить категорию' => '',
    'Добавить статью' => '',
    'Информация' => '',
    'Информация - Добавить категорию' => '',
    'Информация - Категории' => '',
    'Информация - Просмотр статьи' => '',
    'Информация - Статьи' => '',
    'Разработчику' => '',
    'Управление' => '',
];
